#+TITLE: BrainDump: Anurag Peshne
#+OPTIONS: toc:nil num:nil creator:t author:nil timestamp:nil
#+HTML_HEAD: <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+INCLUDE: "../assets/ga.org"
#+EXPORT_OPTIONS: comments:t

* Hello
  My name is Anurag Peshne. I'm interested in Programing Languages, Operating
  Systems, Text Editors (particularly Vim and Emacs), Lisp and Functional
  Programing.

  I'm a graduate student at University of Florida; I studied Computer Science at
  [[http://vnit.ac.in/][VNIT]] and have experience working with server teams at multinational corporation
  as well as a startup.

  Besides CS, I'm interested in cycling and [[https://www.flickr.com/photos/anuragpeshne/][photography]]. Moon and time lapsed
  photography are my favourites.

  Here's my [[./now.org][/now]] page: the things I'm upto these days.

* Projects
  Here are some of my somewhat working projects:
  - [[https://github.com/anuragpeshne/vKeyboard][vKeyboard]]
   Share keyboard accoss computers over the network.
  - [[https://github.com/anuragpeshne/austerity][austerity]]
   Bunch of shell scripts to restrict access to time /wasting/ websites.
  - [[https://github.com/font8x8][font8X8]]
   Language agnostic monochrome bitmap font for rendering.
  - [[https://github.com/anuragpeshne/airLift][airLift]]
   Automated file sharing over network.
  - [[https://github.com/anuragpeshne/funJmp][funJmp]]
   Jump to function definition in Vim using Regex.
  - [[https://github.com/anuragpeshne][github.com/anuragpeshne]]
   Rest of the projects can be found at my github repo.

* Essays
  - [[file:./essays/gitTutorial.org][Git Tutorial]]
  - [[file:./essays/permissions101.org][Unix Permissions 101]]
  - [[file:./essays/keywords.org][Keywords]]
  - [[file:./essays/emacsSpeed.org][Speeding Up Emacs]]
  - [[file:./essays/asynchronous.org][Asynchronous]]
  - [[https://github.com/anuragpeshne/Y-Combinator/blob/master/Ycombinator.org][Y Combinator]]
  - [[file:./essays/index.org][/essays]] Rest of the essays

* Contact
  Feel free to drop me a mail at [[mailto:anurag.peshne@gmail.com][anurag.peshne@gmail.com]], find me on [[https://www.linkedin.com/in/anuragpeshne][Linkedin]],
  [[https://github.com/anuragpeshne/][Github]] or browse my [[https://www.flickr.com/photos/anuragpeshne/][photostream]].

  [[file:./anurag.pub][Here's]] my public PGP
#+BEGIN_SRC PGP_key
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: GPGTools - https://gpgtools.org

mQINBFehiAUBEADs2elnltHjihsK12vLVVaCxB2+Nc/I9YU6uMOuEdFVfSkkmvE3
ID9DXAJbP3U3JR3xI5Vfvi4RDAXwEv9d0d9NBOf8WJDVBNg4XJ9N6vaQuEEEgMqp
YQG2q7exL8P8jdyRrUpw/RnMnA5wthSNKxaO3yo4LGrlgiA8xqzA6LYcCewKqHjg
9B2nk6fYmNtRuUDZmJfTYt+tUWgjiu8A1ArLmVHD1Rxrr3589K63NTfUKAY133nS
3VFCjJFnZLhD2LxqCtXavcr4TUf8w0Bzc43rAc3rrjcqSZZ86Df1ffMkrb1+GqlQ
vUkGPJF6VHuzXwsOpiJQNNSagUHdNCpTTHmMTtmfWDfBfW0n/IAxTmA1ok/9V99u
ivRA+LAML1Y1rzXveMMhhgUcic6MSDc0/o97bKMs3dOFnG+nkaJGz45FBu4HOkyT
5fbSENPl+uiG0jkbxfLL5A+APRF9KN+2qTKhqcioG58InMCXb8JSs0YCxPXj/uyB
waC+mooa0IHeQmwRgtRddYER0EZRa44oTnWzvy2RatJ9ARCCRTfq5d+3u94kua4x
ium5/pYnZTpZm3YNyCF+4EPlKIvqkM9KCXL1heJr5e3GdqVLWf2a6D2D7c2I/13s
74NKXAm7GYRCVVC/g/FHHxEicHo1s3LNrlYWHx7N85BsPsIRLMToo62jUQARAQAB
tCdhbnVyYWcgcGVzaG5lIDxhbnVyYWcucGVzaG5lQGdtYWlsLmNvbT6JAj0EEwEK
ACcFAlehiAUCGwMFCQeGH4AFCwkIBwMFFQoJCAsFFgIDAQACHgECF4AACgkQeL2E
0bpd5Tqezw//UDR5SbNK7J1RUX1Rv3VA+TcqWlK8CtR1R4rTXCaSgmIInVpD+hAX
z5EuCa/lT4+iS735xq7/zfGsNkpnT9ntEYPuU/93wMiakBmMVHHCl1+ZwXTsDkav
ZaHs8TUe8X7j3uRYQCjVQN1eGihtU2LG18S7a4BvI7CEQgigg3woyj9qRpxjKpQg
jrY/OQPRVtvI8Kd9rGnqfms+j1wUzuY1M0mJ4qRVjGQaoQrzFhgMbuRK3WA+aYFy
C+W51Q47ARgiCnwTeJMQbsS384cyphzAsPPd9Zy4sGabofFVQdRsN1WKacaILw5f
lQ0+J/AsjPDV0kURlz6gBKjST75baqexp2jU7STlr2buEmd8+VxntvuoYz7de9h9
XwD7Rt5/XUzzlK+ERx1qmVMX9xPaYkC7j/oHkcGO1GcGn2qo++GvycmSJHA0TGva
2H4z38hMdg3k8fNrW/rsl+WY0/IaKhwd6BMV0RE9AEqfE0mcql+Wb/RIXKGPFrDu
fvnmDWhxmRJaQqDrxlDAqQok2TOYuQ520VIAzLE68Akhk3/LOYEiqn29bEZf+wV0
CxQZHMEN8xUNpG1ZUBBtBgig3PQixdFuNBrh/cOIJSjJjiZmdozvnZvI2dSz/cCI
CKecfZVq/lD70FxKSk2O5W8SAawFiUkObHUoiAFkdq/7Pj4K0q2ZocC5Ag0EV6GI
BQEQAMB5VWF5rbVqC9q5/BnyxdzzfSZBjCpB2ujmy7yV0ALm1U52F7zv0hS4G1Li
IssmuH+unWVpzWrdNtTzy1i1dVBn6j8lEmt8fXUkj5ynQCGCL+2EjgxlLvredgGi
AzdmaIKZH3goz/JgJap6xab/gQUHFb4E+VI+TM4sjaefdTyeHK1i43vYL4qjyKZl
8SfqZu9hxfnC3HL4mnHBvkiC5A2CEqE40WWc05ey+kOQPYw4+Qoit+hgfK163XBS
lpFVyMTPMC7/vHeB2fOgK8EimM2YCuOSMjTlCaTtQmi0MQCbJsaSsCPA++imRbk4
cAbxmowfIW3GYk/bUX1ZSG2z7NLx2k6tSr3LxhBUyJQFwD21oqAfQU0ULkUBWPRB
yziLtO2KEsey/0PPN2MgVZxBcTIeQ86VX1rx7IhbuqnykA2FT/VaTob9VMKpm8ps
Cb8+FLmWUh/O0VlOhnWjSVCZBn9zbFW5nbxlalXmEVJ6mfAI6th9NIwJmww0m/qW
Kglu+5V2bNfw6A5wL3nVOAu9wdPf1juHIfl9ltDN4LikAPZCwACGIKKAXYUQMe2j
+WT4WCMPJ9AL08ClqmBM7IYoo6TYwp5u+3nLb72HL7UlBO4SP8gBGF1TIHolzE9l
tWadI9VBnIqT+baTSVnLzL+QPaJ4btf7nkCeWWv4d+T7AlghABEBAAGJAiUEGAEK
AA8FAlehiAUCGwwFCQeGH4AACgkQeL2E0bpd5TprVg/+LuepLiMUDlVpMocL1GS7
0cDFA9Ixh+P9lazcNKwGEHrZ/eNfHpyhWTZpjjOWQQqqkmrQBNrBSc34/XdpM64I
txG+7I1y05va6hmHOO8v5ecRCH+Xe3DDy3CHgKvFmfuFHVi5UrdMdVBKcns+YDDo
eqPuj6y5SG2qtYUNLNmUbe/QOAVEBC34viFVdC5uBjDf7yuDRzrfpS89S4DFCDi6
qxHC9UeVZtTW1E3YczbRnaDPSETwUex/AT2X4xlABUsc2F7agUQdxW2QREpGsSRY
UJY4ce9y6Kx7Z2ddn4FuddFSjunU4URcT06QUMVKmnr9S6+3nPpZo1USZkNY4vbu
oWDnKPcomSQ01CnV8DsMCJfZbDzrc/0iqWYMjiUMX5PpafMj9qnaHIKzgxkoBF5g
0F9dhwyIMtxI1cE/UdFCkbr9i5VCzQWgDBX2RkXkWIis5E6V7SCI72j8IXT1n2+s
i+qerBJC15aHNKSzfwTnFu8YaSqc1Hxr00Y2/Ip/Ts0ABZflgZvu+zXol8xv28c/
4OFWGL/aE7ck7gj5gIM4VpHZMTq1Cas9JExw1bQ3wCMYzadSd3cbjOMS+FkOv/Pp
Tg5ESHbcTbhsLwr5RiJVOaA6e9k4/tOq0tso5KmW4oelFkpZk5iep/OJ3Iapv/MP
gq2IfBBoj8rLyA4KPnWyMnA=
=4H3r
-----END PGP PUBLIC KEY BLOCK-----
#+END_SRC
