#+TITLE: BrainDump: Anurag Peshne
#+OPTIONS: toc:nil num:nil creator:t author:nil timestamp:nil
#+HTML_HEAD: <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css' />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />
#+INCLUDE: "../assets/ga.org"
#+EXPORT_OPTIONS: comments:t

* Hello
  My name is Anurag Peshne. I'm interested in Programing Languages, Operating
  Systems, Text Editors (particularly Vim and Emacs), Lisp and Functional
  Programing.

  I'm a graduate student at University of Florida; I studied Computer Science at
  [[http://vnit.ac.in/][VNIT]] and have experience working with server teams at multinational corporation
  as well as a startup.

  Besides CS, I'm interested in cycling and [[https://www.flickr.com/photos/anuragpeshne/][photography]]. Moon and time lapsed
  photography are my favourites.

  Here's my [[./now.org][/now]] page: the things I'm upto these days.

* Projects
  Here are some of my somewhat working projects:
  - [[https://github.com/anuragpeshne/vKeyboard][vKeyboard]]
   Share keyboard accoss computers over the network.
  - [[https://github.com/anuragpeshne/austerity][austerity]]
   Bunch of shell scripts to restrict access to time /wasting/ websites.
  - [[https://github.com/font8x8][font8X8]]
   Language agnostic monochrome bitmap font for rendering.
  - [[https://github.com/anuragpeshne/airLift][airLift]]
   Automated file sharing over network.
  - [[https://github.com/anuragpeshne/funJmp][funJmp]]
   Jump to function definition in Vim using Regex.
  - [[https://github.com/anuragpeshne][github.com/anuragpeshne]]
   Rest of the projects can be found at my github repo.

* Essays
  - [[file:./essays/tcp2c10k.org][TCP to C10k: HTTP Server Implementation]]
  - [[file:./essays/gitTutorial.org][Git Tutorial]]
  - [[file:./essays/permissions101.org][Unix Permissions 101]]
  - [[file:./essays/keywords.org][Keywords]]
  - [[file:./essays/emacsSpeed.org][Speeding Up Emacs]]
  - [[file:./essays/asynchronous.org][Asynchronous]]
  - [[https://github.com/anuragpeshne/Y-Combinator/blob/master/Ycombinator.org][Y Combinator]]
  - [[file:./essays/index.org][/essays]] Rest of the essays

* Notes
  Bunch of notes to me.
  - [[file:./notes/plp.org][Programming Language Principles]]
* Contact
  Feel free to drop me a mail at [[mailto:anurag.peshne@gmail.com][anurag.peshne@gmail.com]], find me on [[https://www.linkedin.com/in/anuragpeshne][Linkedin]],
  [[https://github.com/anuragpeshne/][Github]] or browse my [[https://www.flickr.com/photos/anuragpeshne/][photostream]].

  [[file:./anurag.pub][Here's]] my public PGP
#+BEGIN_SRC PGP_key_fingerprint
E060 17E9 0ABB B748 2099  C617 78BD 84D1 BA5D E5
#+END_SRC
